#!/bin/sh

case "$(uname)" in
    Darwin*)
        cd $HOME/Desktop

        mkdir -p                        $HOME/Pictures/Screenshots/
        mv -f Screenshot*.png           $HOME/Pictures/Screenshots/ 2>/dev/null

        mv -f *.{jpg,jpeg,png,gif}      $HOME/Pictures/             2>/dev/null

        mv -f *.{mov,avi,mp4}           $HOME/Movies/               2>/dev/null

        mv -f *.{mp3,ogg}               $HOME/Music/                2>/dev/null

        mv -f *.{txt,pdf,docx,md,xlsx}  $HOME/Documents/            2>/dev/null
        mv -f *.json                    $HOME/Documents/            2>/dev/null

        mv -f *.excalidraw              $HOME/Documents/Excalidraw/ 2>/dev/null

        mv -f *.{gz,,pat,zip}           $HOME/Documents/Archives/   2>/dev/null

        rm -rf *.{dmg,webp,p7b,log,pub,zip,pkg,webloc,fwl,html,ics,csv,yml}
        rm -rf *.{tar,xml,gz,avif,tgz}

        find ~/Desktop -type d -maxdepth 1 -mindepth 1 -prune \
            -exec mv "{}" ~/Documents \;
        ;;
esac
