#!/bin/sh

case "$(uname)" in
    Darwin*)
        cd $HOME/Desktop

        mkdir -p                $HOME/Pictures/Screenshots/
        mv -f Screenshot*.png   $HOME/Pictures/Screenshots/ 2>/dev/null

        mv -f *.{jpg,png}       $HOME/Pictures/             2>/dev/null

        mv -f *.{txt,pdf}       $HOME/Documents/            2>/dev/null

        rm -rf *.{dmg,webp,p7b,log,pub,zip}
        ;;
esac
