#!/bin/bash
set -euo pipefail

# if you don't like ~/develpment simply:
#   export CLONEINTO_ROOT=/path/to/your/preference
rootDir=${CLONEINTO_ROOT:-~/development}
cloneURL="${1:?missing git clone url}"

# determine which editor to use
# priority: command line arg > env var > code-insiders > code
editor=""
if [ -n "${2:-}" ]; then
    editor="$2"
elif [ -n "${CLONE_INTO_DIR_EDITOR:-}" ]; then
    editor="$CLONE_INTO_DIR_EDITOR"
elif type code-insiders 2>/dev/null; then
    editor="code-insiders"
elif type code 2>/dev/null; then
    editor="code"
fi

# make sure the rootDir exists, and go there
mkdir -p "${rootDir}"
cd "${rootDir}"

# anything that looks like a remote git repo
pattern='^.+:(.*)/(.*).git$'

if [[ "$cloneURL" =~ $pattern ]]; then
    if [ -d "${rootDir}/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}" ]; then
        echo "# project already exists: ${rootDir}/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}"
    else
        echo "# cloning ${cloneURL} into ${rootDir}/${BASH_REMATCH[1]}…"
        mkdir -p "${BASH_REMATCH[1]}"
        git -C "${BASH_REMATCH[1]}" clone "${cloneURL}"
        echo "# repository cloned to: ${rootDir}/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}"
    fi
else
    echo "# unsupported git uri: $cloneURL"
fi

# if we have an editor selected, open the new repo
if [ -n "$editor" ] && [ -d "${rootDir}/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}" ]; then
    echo "# opening ${rootDir}/${BASH_REMATCH[1]}/${BASH_REMATCH[2]} in ${editor}…"
    "$editor" "${rootDir}/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}"
fi
