---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # use this and NOT the one in jumanjihouse; it supports the enable/disable
  # markup
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      # - id: bundler-audit
      # - id: check-mailmap
      # - id: fasterer
      # - id: forbid-binary
      # - id: forbid-space-in-indent
      - id: git-check
      - id: git-dirty
      # - id: markdownlint
      # - id: reek
      # - id: require-ascii
      # - id: rubocop
      # - id: script-must-have-extension
      # - id: script-must-not-have-extension
      - id: shellcheck
      # - id: shfmt

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.1
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.1.0
    hooks:
      - id: yamlfmt
        args: [--offset, '2', --mapping, '2', --sequence, '4']

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v0.8.3
    hooks:
      #
      # Go Build
      #
      - id: go-build-mod
      # - id: go-build-pkg
      # - id: go-build-repo-mod
      # - id: go-build-repo-pkg
      #
      # Go Test
      #
      - id: go-test-mod
      # - id: go-test-pkg
      # - id: go-test-repo-mod
      # - id: go-test-repo-pkg
      #
      # Go Vet
      #
      # - id: go-vet
      - id: go-vet-mod
      # - id: go-vet-pkg
      # - id: go-vet-repo-mod
      # - id: go-vet-repo-pkg
      #
      # Formatters
      #
      - id: go-fmt
      - id: go-imports
      - id: go-returns
      #
      # Style Checkers
      #
      - id: go-lint
      - id: go-critic
      #
      # GolangCI-Lint
      # - Fast Multi-Linter
      # - Can be configured to replace MOST other hooks
      # - Supports repo config file for configuration
      # - https://github.com/golangci/golangci-lint
      #
      # - id: golangci-lint
      - id: golangci-lint-mod
      # - id: golangci-lint-pkg
      # - id: golangci-lint-repo-mod
      # - id: golangci-lint-repo-pkg
