#!/bin/sh
# vim:filetype=sh
set -eu

# stolen from https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
setup_color() {
    # Only use colors if connected to a terminal
    if [ -t 1 ]; then
        RED=$(printf '\033[31m')
        GREEN=$(printf '\033[32m')
        RESET=$(printf '\033[m')
    else
        RED=""
        GREEN=""
        RESET=""
    fi
}

# stolen from install.sh
# can't factor into a shared file as we would like to have the install.sh
# standalone
unset current_session_shellrc
current_session_shellrc() {
    current_shell="${SHELL##*/}"

    case "${current_shell}" in
        zsh)
            current_rcfile=~/.zshrc
            ;;

        bash)
            case "$(uname)" in
                Darwin*)
                    current_rcfile=~/.bash_profile
                    ;;
                *)
                    current_rcfile=~/.bashrc
                    ;;
            esac
            ;;

        *)
            current_rcfile="~/.unknownrc"
            ;;
    esac
}

show_updated_message() {
    current_session_shellrc
    printf '%s' "$GREEN"
    cat <<"EOF"
           _             _    _                    _
          ( )           (_ ) (_ )                 ( )
      ___ | |__     __   | |  | |  _ __   ___    _| |
    /',__)|  _ `\ /'__`\ | |  | | ( '__)/'___) /'_` |
    \__, \| | | |(  ___/ | |  | | | |  ( (___ ( (_| |
    (____/(_) (_)`\____)(___)(___)(_)  `\____)`\__,_)
                                ....is up to date!
EOF

    cat <<EOF

    You are running from:
        ${branch}

    Updates will activate in a new shell, or if you source your rcfile:
        source ${current_rcfile}
EOF
    printf '%s' "$RESET"
}

update_submodules() {
    # we might not have any submodules, but it would be nice to check
    _count=$(git -C "${rcdir}" submodule |wc -l)
    if [ "${_count}" -gt 0 ]; then
        echo "[shellrcd] Updating submodules…"
        git -C "${rcdir}" submodule update --recursive
    fi
}

main() {
    setup_color

    rcdir=~/.shellrc.d

    cd "${rcdir}"

    if [ "$(git diff --stat)" != '' ]; then
        echo "${RED}[ERROR] uncommitted changes in ${rcdir}${RESET}"
        exit 1;
    fi

    # get the branch we're on
    branch="$(git rev-parse --abbrev-ref HEAD)"

    # not on master?
    if [ "${branch}" != "master" ]; then
        echo "[shellrcd] Switching back to 'master'…"
        git checkout master
    fi

    echo "[shellrcd] Pulling recent changes into $(git rev-parse --abbrev-ref HEAD)…"
    git pull --rebase --ff-only --prune

    if [ "${branch}" != "master" ]; then
        # check out the branch again
        # update the branch
        # rebase from master
        echo "[shellrcd] Switching back to '${branch}'…"
        git checkout "${branch}"
        echo "[shellrcd] Pulling recent changes into ${branch}…"
        git pull --rebase --ff-only --prune
        echo "[shellrcd] Rebasing master and ${branch}…"
        git rebase master
    fi

    update_submodules

    show_updated_message
}

main "$@"
